upstream payment_api {
  server api-1:8080 max_fails=1 fail_timeout=2s;
  server api-2:8080 max_fails=1 fail_timeout=2s;
}
server {
  listen 80;
  location / { proxy_pass http://payment_api; proxy_next_upstream error timeout http_502 http_503 http_504; }
}
